INSERT INTO CURRENCY_CONVERSION(ID,AMOUNT,HOME_CURRENCY,TARGET_CURRENCY,TIMEOFDAY) VALUES(25,10,'USD','GBP','2020-06-11');
INSERT INTO CURRENCY_CONVERSION(ID,AMOUNT,HOME_CURRENCY,TARGET_CURRENCY,TIMEOFDAY) VALUES(26,13,'EUR','GBP','2020-06-10');
INSERT INTO CURRENCY_CONVERSION(ID,AMOUNT,HOME_CURRENCY,TARGET_CURRENCY,TIMEOFDAY) VALUES(27,10,'EUR','GBP','2020-06-18');
INSERT INTO CURRENCY_CONVERSION(ID,AMOUNT,HOME_CURRENCY,TARGET_CURRENCY,TIMEOFDAY) VALUES(28,100,'EUR','GBP','2020-06-18');
INSERT INTO CURRENCY_CONVERSION(ID,AMOUNT,HOME_CURRENCY,TARGET_CURRENCY,TIMEOFDAY) VALUES(29,25,'USD','GBP','2020-06-11');
